radio/#1
awesome-academy/pp1804_imusic pull request #31
Opened 2019-03-01 14:14 UTC by caoxuanhoi

#About

# (Technical changes)

# Relative URL

# UI changes

# TODO

# Others

2019-03-15 14:13 UTC, caoxuanhoi commented
ready

2019-03-15 16:50 UTC, tranvanmy requested changes
file demo.js là file nào đấy em

2019-03-15 16:50 UTC, tranvanmy commented on public/css/my-style.css
>  }
convention

2019-03-15 16:50 UTC, tranvanmy commented on resources/views/admin/page/index.blade.php
> +                            <a class="button popup-with-zoom-anim" href="javascript:void(0)" id="music{{ $song->id }}" onclick="demo({{ $song->id }})" data-url="{{ $song->path }}"><img src="{{ $artis
đổi lại tên function nhé, đặt tên function có ý nghĩa

2019-03-15 16:50 UTC, tranvanmy commented on resources/views/frontend/trangchu.blade.php
> +		<script src="source/js/demo.js"></script>
đổi lại tên file nhé

2019-03-18 11:35 UTC, caoxuanhoi commented
ready

2019-03-18 11:36 UTC, merged